services:
    data-web:
        image: ghcr.io/niggelgame/co2-data-image:34
        ports:
            - "8000:8000"
        volumes:
            - .:/root/data
        environment:
            - DATA_SQLITE_PATH=data/sqlite.db
            - DATA_FIREBASE_CREDENTIALS_PATH=data/serviceAccountKeys.json
        restart: always
    sensoring:
        depends_on:
            - data-web
        image: ghcr.io/niggelgame/co2-sensoring-image:31
        environment:
            - DATA_BASE_URL=http://data-web:8000
        privileged: true
        restart: always
    homebridge:
        restart: always
        image: oznu/homebridge
        environment:
            - PGID=1000
            - PUID=1000
            - HOMEBRIDGE_CONFIG_UI=1
            - HOMEBRIDGE_CONFIG_UI_PORT=8581
            - TZ=Europe/Berlin
        network_mode: host
        volumes:
            - ./volumes/homebridge:/homebridge