services:
    data-web:
        image: ghcr.io/niggelgame/co2-data-image:7
        ports:
            - "8000:8000"
        volumes:
            - .:/root
    sensoring:
        depends_on:
            - data-web
        image: ghcr.io/niggelgame/co2-sensoring-image:11
        environment:
            - DATA_BASE_URL=http://data-web:8000
        devices:
            - "/dev/gpiomem:/dev/gpiomem"