services:
    data-web:
        image: ghcr.io/niggelgame/co2-data-image:23
        ports:
            - "8000:8000"
        volumes:
            - .:/root/data
        environment:
            - DATA_SQLITE_PATH=data/sqlite.db
            - DATA_FIREBASE_CREDENTIALS_PATH=data/serviceAccountKeys.json
    sensoring:
        depends_on:
            - data-web
        image: ghcr.io/niggelgame/co2-sensoring-image:29
        environment:
            - DATA_BASE_URL=http://data-web:8000
        privileged: true